# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup nuget
      run: dotnet nuget add source --username nrweber --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nrweber/index.json"
    - name: Build
      run: dotnet build -c Release ./*.sln
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish Nuget Package
      run: dotnet nuget push ./**/bin/Release/*.nupkg --api-key "$TOKEN"  --source "github"
      env:
        TOKEN: '${{ secrets.GITHUB_TOKEN }}'
